"""Freeze GATE-C1-FUSED-PREPROC-001 without generating or executing fused code."""
from __future__ import annotations
import csv,hashlib,json
from datetime import datetime,timezone
from pathlib import Path
import joblib,numpy as np,pandas as pd,yaml
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/"results/embedded";GATE="GATE-C1-FUSED-PREPROC-001";FUTURE="EXP-EMBED-C1-FUSED-EQUIV-001"
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(name,rows):pd.DataFrame(rows).to_csv(OUT/name,index=False)

def main():
 s14=pd.read_csv(OUT/"stage14_manifest.csv");s14r=pd.read_csv(OUT/"stage14r_manifest.csv");registered=dict(zip(s14.artifact_path,s14.sha256));registered.update(dict(zip(s14r.artifact_path,s14r.sha256)))
 req=["artifacts/models/BASE-FIXED-C1-001.joblib","embedded/preprocessing_spec.yaml","configs/embedded_equivalence_protocol.yaml","results/embedded/stage14_manifest.csv","results/embedded/stage14r_manifest.csv","data/manifests/embedded_golden_vectors.csv","data/manifests/embedded_boundary_vectors.csv","results/embedded/stage14_output_equivalence.csv","results/embedded/stage14r_error_decomposition.csv"]
 rows=[]
 for rel in req:
  p=ROOT/rel;actual=sha(p);expected=registered.get(rel)
  if rel.startswith("artifacts/models"):
   q=pd.read_csv(OUT/"stage14r_input_manifest.csv");expected=q.loc[q.artifact_path.eq(rel),"sha256"].iloc[0]
  if expected and actual!=expected:raise RuntimeError(f"BLOCKED_INPUT_INTEGRITY {rel}")
  rows.append({"gate_id":GATE,"artifact_path":rel,"sha256":actual,"expected_sha256":expected or actual,"verification_status":"VERIFIED"})
 pipe=joblib.load(ROOT/req[0]);s=pipe.named_steps["scaler"];m=pipe.named_steps["model"]
 assert s.mean_.shape==s.scale_.shape==(128,) and m.coef_.shape==(6,128) and m.intercept_.shape==(6,) and list(m.classes_)==[1,2,3,4,5,6]
 scaler_hash=hashlib.sha256(np.concatenate([s.mean_,s.scale_,s.var_]).astype("<f8").tobytes()).hexdigest();expected=pd.read_csv(OUT/"stage13_preprocessing_inventory.csv").query("model_id=='MODEL-C1'").constants_sha256.iloc[0]
 if scaler_hash!=expected:raise RuntimeError("BLOCKED_INPUT_INTEGRITY scaler")
 class_hash=hashlib.sha256(np.asarray(m.classes_,dtype="<i8").tobytes()).hexdigest();rows += [{"gate_id":GATE,"artifact_path":"MODEL-C1:frozen_scaler_constants","sha256":scaler_hash,"expected_sha256":expected,"verification_status":"VERIFIED"},{"gate_id":GATE,"artifact_path":"MODEL-C1:class_order_int64","sha256":class_hash,"expected_sha256":class_hash,"verification_status":"VERIFIED"}];write("c1_fused_protocol_input_manifest.csv",rows)
 algebra=[{"gate_id":GATE,"component":"REFERENCE_STANDARDIZATION","equation":"z_i=(x_i-mean_i)/scale_i","shape":"128","source":"frozen StandardScaler","future_runtime":"NOT_MATERIALIZED_BY_F0"},{"gate_id":GATE,"component":"REFERENCE_SCORE","equation":"score_c=intercept_c+sum_i(coefficient[c,i]*z_i)","shape":"6","source":"frozen LogisticRegression","future_runtime":"REPLACED_ALGEBRAICALLY"},{"gate_id":GATE,"component":"FUSED_WEIGHT","equation":"w_raw[c,i]=coefficient[c,i]/scale_i","shape":"6x128","source":"offline float64 frozen parameters","future_runtime":"FLOAT32_CONSTANT"},{"gate_id":GATE,"component":"FUSED_BIAS","equation":"b_raw[c]=intercept[c]-sum_i(coefficient[c,i]*mean_i/scale_i)","shape":"6","source":"offline float64 frozen parameters","future_runtime":"FLOAT32_CONSTANT"},{"gate_id":GATE,"component":"FUSED_SCORE","equation":"score_raw[c]=b_raw[c]+sum_i(w_raw[c,i]*raw_fp32[i])","shape":"6","source":"C1-FUSED-F0","future_runtime":"FLOAT32_ASCENDING_FEATURE_ORDER"},{"gate_id":GATE,"component":"PROBABILITY","equation":"stable_softmax(score_raw)","shape":"6","source":"confirmed multinomial semantics","future_runtime":"FLOAT32"}];write("c1_fused_algebraic_spec.csv",algebra)
 ops=[{"architecture":"EXPLICIT_PIPELINE","scaler_subtractions":128,"scaler_divisions":128,"classifier_multiplications":768,"classifier_accumulations":768,"bias_additions":6,"total_primary_arithmetic":1798,"runtime_prediction_constants":1030,"transformed_buffer_elements":128,"measurement_type":"DERIVED_ANALYTICAL"},{"architecture":"C1-FUSED-F0","scaler_subtractions":0,"scaler_divisions":0,"classifier_multiplications":768,"classifier_accumulations":768,"bias_additions":6,"total_primary_arithmetic":1542,"runtime_prediction_constants":774,"transformed_buffer_elements":0,"measurement_type":"DERIVED_ANALYTICAL"},{"architecture":"FUSED_MINUS_EXPLICIT","scaler_subtractions":-128,"scaler_divisions":-128,"classifier_multiplications":0,"classifier_accumulations":0,"bias_additions":0,"total_primary_arithmetic":-256,"runtime_prediction_constants":-256,"transformed_buffer_elements":-128,"measurement_type":"DERIVED_ANALYTICAL"}];write("c1_fused_operation_analysis.csv",ops)
 storage=[{"component":"fused_weights","elements":768,"bytes_fp32":3072,"required_for_prediction":True,"required_for_future_xai":True,"evidence_state":"DERIVED_FROM_ARCHITECTURE"},{"component":"fused_biases","elements":6,"bytes_fp32":24,"required_for_prediction":True,"required_for_future_xai":False,"evidence_state":"DERIVED_FROM_ARCHITECTURE"},{"component":"scaler_means","elements":128,"bytes_fp32":512,"required_for_prediction":False,"required_for_future_xai":True,"evidence_state":"DERIVED_FROM_ARCHITECTURE"},{"component":"scaler_scales","elements":128,"bytes_fp32":512,"required_for_prediction":False,"required_for_future_xai":False,"evidence_state":"DERIVED_FROM_ARCHITECTURE"},{"component":"raw_input_buffer","elements":128,"bytes_fp32":512,"required_for_prediction":True,"required_for_future_xai":True,"evidence_state":"DERIVED_FROM_ARCHITECTURE"},{"component":"transformed_feature_buffer","elements":0,"bytes_fp32":0,"required_for_prediction":False,"required_for_future_xai":False,"evidence_state":"DERIVED_BUFFER_REDUCTION"},{"component":"score_buffer","elements":6,"bytes_fp32":24,"required_for_prediction":True,"required_for_future_xai":True,"evidence_state":"DERIVED_FROM_ARCHITECTURE"},{"component":"probability_buffer","elements":6,"bytes_fp32":24,"required_for_prediction":True,"required_for_future_xai":False,"evidence_state":"DERIVED_FROM_ARCHITECTURE"}];write("c1_fused_storage_analysis.csv",storage)
 xai=[{"component":"FEATURE_CONTRIBUTION","reference_semantics":"coefficient[c,i]*((x_i-mean_i)/scale_i)","raw_domain_equivalent":"w_raw[c,i]*(x_i-mean_i)","incorrect_conflation":"w_raw[c,i]*x_i","baseline_offset_semantics":"-w_raw[c,i]*mean_i belongs to centered feature contribution","intercept_semantics":"fused bias contains intercept plus aggregate centering offset for prediction; do not assign full fused bias to any feature","future_scope":"SEPARATE_XAI_EXPERIMENT","status":"SPECIFIED_NOT_EXECUTED"},{"component":"DEPENDENCY_ORDER","reference_semantics":"prediction and explanation are separate claims","raw_domain_equivalent":"validate fused inference first","incorrect_conflation":"fused inference pass implies XAI pass","baseline_offset_semantics":"means retained separately if XAI is later implemented","intercept_semantics":"preserve original baseline decomposition","future_scope":"A_INFERENCE_FIRST_WITHOUT_XAI","status":"FROZEN"}];write("c1_fused_xai_semantics.csv",xai)
 claims=[{"claim_id":"C-EMBED-C1-FUSED-01","future_experiment_id":FUTURE,"claim":"Raw-input FP32 affine C1 reproduces scores and probabilities within prospectively frozen limits.","initial_status":"UNSUPPORTED","required_evidence":"parameter integrity plus score/probability criteria"},{"claim_id":"C-EMBED-C1-FUSED-02","future_experiment_id":FUTURE,"claim":"Fused FP32 C1 preserves 100% golden and boundary decisions.","initial_status":"UNSUPPORTED","required_evidence":"100% golden and boundary agreement"},{"claim_id":"C-EMBED-C1-FUSED-XAI-01","future_experiment_id":"SEPARATE_AFTER_FUSED_INFERENCE","claim":"Baseline-preserving raw-domain C1 local contributions reproduce Stage-09 explanations.","initial_status":"UNSUPPORTED","required_evidence":"separate prospective XAI equivalence experiment"}];write("c1_fused_claim_registry.csv",claims)
 decision=[{"gate_id":GATE,"timestamp":datetime.now(timezone.utc).isoformat(),"gate_status":"FROZEN","performance_experiment_status":"NOT_EXECUTED","future_experiment_id":FUTURE,"decision":"AUTHORIZE EXP-EMBED-C1-FUSED-EQUIV-001","candidate":"C1-FUSED-F0_ONLY","xai_scope":"INFERENCE_FIRST_XAI_SEPARATE","quantization":"NOT_EXECUTED","mcu_execution":"NOT_EXECUTED","compiled_flash":"NOT_MEASURED","mcu_sram":"NOT_MEASURED","mcu_latency":"NOT_MEASURED","energy":"NOT_MEASURED"}];write("c1_fused_gate_decision.csv",decision)
 artifacts=["docs/embedded/C1_FUSED_PREPROCESSING_ARCHITECTURE.md","docs/embedded/C1_FUSED_EQUIVALENCE_PROTOCOL.md","configs/c1_fused_equivalence.yaml"]+[f"results/embedded/{name}" for name in ["c1_fused_protocol_input_manifest.csv","c1_fused_algebraic_spec.csv","c1_fused_operation_analysis.csv","c1_fused_storage_analysis.csv","c1_fused_xai_semantics.csv","c1_fused_claim_registry.csv","c1_fused_gate_decision.csv"]]
 manifest=[]
 for rel in artifacts:
  p=ROOT/rel;manifest.append({"gate_id":GATE,"artifact_path":rel,"sha256":sha(p),"evidence_state":"PROTOCOL_FROZEN","performance_result":"NOT_EXECUTED"})
 write("c1_fused_protocol_manifest.csv",manifest)
 print(json.dumps(decision[0],indent=2))
if __name__=="__main__":main()
