"""Register Stage 11 evidence, candidate claims, and exactly one research decision."""
from __future__ import annotations
import csv,hashlib,subprocess
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];EID="EXP-XAI-STABILITY-001"
def rows(p):
 with p.open(encoding="utf-8-sig",newline="") as f:return list(csv.DictReader(f))
def append(p,fields,row):
 with p.open("a",encoding="utf-8",newline="") as f:csv.DictWriter(f,fieldnames=fields).writerow(row)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
commit=subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip();legacy=ROOT/"results/registry/experiment_registry.csv";old=rows(legacy);fields=list(old[0])
if not any(r["experiment_id"]==EID for r in old):append(legacy,fields,{"experiment_id":EID,"timestamp":datetime.now(timezone.utc).isoformat(),"research_question":"How stable are Stage-09 explanations under chronological sensor drift after conditioning on input and model change?","protocol":"FROZEN_STAGE11_STABILITY","model":"MODEL-C1..C4","representation":"GLOBAL_SENSOR_FAMILY_LOCAL_MATCHED","train_batches":"1_REFERENCE_ONLY","validation_batches":"","test_batches":"2-10_GLOBAL;2,6,10_LOCAL","seed":"42","dataset_hash":old[0]["dataset_hash"],"split_hash":next(r["split_hash"] for r in old if r["experiment_id"]=="BASE-FIXED-C1-001"),"config_hash":sha(ROOT/"configs/xai_stability_protocol.yaml"),"git_commit":commit,"environment":"artifacts/explanations/EXP-XAI-0001/environment.json","status":"COMPLETED","metrics_artifact":"results/xai/stage11_stability_summary.csv","model_artifact":"","notes":"No retraining; chronological permutation vectors; natural-neighbor and one-to-one matched cross-sectional local analysis; 1000 bootstrap replicates."})
claims=ROOT/"paper/claim_evidence_matrix.csv";cr=rows(claims);cf=list(cr[0]);candidate=[("C-XAI-STAB-01","Top-K explanation rankings remain more similar across adjacent batches than widely separated anchor comparisons.","adjacent_minus_far_anchor_jaccard_ci_low_gt_0","results/xai/stage11_global_rank_stability.csv"),("C-XAI-STAB-02","Explanation change increases as measured sensor-distribution shift increases across all eligible models.","explanation_distance_vs_input_change_spearman_ci_low_gt_0","results/xai/stage11_bootstrap_ci.csv"),("C-XAI-STAB-03","Explanation stability differs between correct and misclassified predictions.","correct_minus_misclassified_distance_ci_excludes_0","results/xai/stage11_local_neighbor_stability.csv"),("C-XAI-STAB-04","Physical sensor-level attribution change increases systematically with chronological input drift across eligible models.","sensor_distance_vs_input_change_spearman_ci_low_gt_0","results/xai/stage11_sensor_stability.csv"),("C-XAI-STAB-05","Stage-10 fidelity and Stage-11 stability are positively associated across matched model/method analyses.","matched_fidelity_stability_spearman_ci_low_gt_0","results/xai/stage11_fidelity_stability_link.csv")]
for cid,text,metric,artifact in candidate:
 if not any(r["claim_id"]==cid for r in cr):append(claims,cf,{"claim_id":cid,"candidate_claim":text,"experiment_id":EID,"dataset_hash":old[0]["dataset_hash"],"split_hash":next(r["split_hash"] for r in old if r["experiment_id"]=="BASE-FIXED-C1-001"),"config_hash":sha(ROOT/"configs/xai_stability_protocol.yaml"),"metric":metric,"result_artifact":artifact,"figure":"","git_commit":commit,"status":"UNSUPPORTED"})
dec=ROOT/"results/decisions/research_decisions.csv";dr=rows(dec);df=list(dr[0])
if not any(r["decision_id"]=="DEC-STAGE11-001" for r in dr):append(dec,df,{"decision_id":"DEC-STAGE11-001","timestamp":datetime.now(timezone.utc).isoformat(),"research_question":"RQ6","experiment_id":EID,"observation":"Global and local stability are method model scale and context dependent; all broad candidate claims remain unsupported.","evidence_artifacts":"results/xai/stage11_global_rank_stability.csv|results/xai/stage11_local_neighbor_stability.csv|results/xai/stage11_fidelity_stability_link.csv","interpretation":"Stability cannot substitute for fidelity; cross-batch explanations change substantially and relationships to input drift are model specific.","limitations":"No repeated identical events; selected audit samples; no concentration matching; some undefined constant-vector correlations.","decision":"Preserve mixed and negative evidence; permit preregistration of Stage 12 without changing Stage 10 or 11 claims.","next_experiment":"EXP-XAI-LATENCY-001","git_commit":commit})
print(EID,"registered; five claims UNSUPPORTED; DEC-STAGE11-001 appended")
