"""Register Stage-14R negative repair evidence and one scientific decision."""
from __future__ import annotations
import csv,hashlib,subprocess
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];EID="EXP-EMBED-C1-PREPROC-REPAIR-001"
def rows(p):
 with p.open(encoding="utf-8-sig",newline="") as f:return list(csv.DictReader(f))
def append(p,fields,row):
 with p.open("a",encoding="utf-8",newline="") as f:csv.DictWriter(f,fieldnames=fields).writerow(row)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
commit=subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip();legacy=ROOT/"results/registry/experiment_registry.csv";old=rows(legacy);fields=list(old[0]);base=next(r for r in old if r["experiment_id"]=="BASE-FIXED-C1-001")
if not any(r["experiment_id"]==EID for r in old):append(legacy,fields,{"experiment_id":EID,"timestamp":datetime.now(timezone.utc).isoformat(),"research_question":"Can prospectively defined all-FP32 explicit StandardScaler arithmetic repair C1 under unchanged equivalence criteria?","protocol":"FROZEN_STAGE14R_C1_EXPLICIT_PREPROCESSING_REPAIR","model":"MODEL-C1","representation":"P0_P1_P2_P3_P4_ALL_FP32_EXPLICIT_STANDARDIZATION","train_batches":"NONE","validation_batches":"GOLDEN_AND_BOUNDARY","test_batches":"2,6,10","seed":"DETERMINISTIC","dataset_hash":old[0]["dataset_hash"],"split_hash":base["split_hash"],"config_hash":sha(ROOT/"configs/c1_fp32_preprocessing_repair.yaml"),"git_commit":commit,"environment":"results/embedded/stage14r_build_environment.json","status":"COMPLETED","metrics_artifact":"results/embedded/stage14r_candidate_summary.csv","model_artifact":"embedded/experimental/c1_preprocessing_repair","notes":"Scientific outcome FAILED; no P0-P4 candidate passed universal frozen preprocessing criteria. Stage-14 failure preserved; no C4 modification, quantization, or MCU execution."})
claims=ROOT/"paper/claim_evidence_matrix.csv";cr=rows(claims);cf=list(cr[0]);defs={"C-EMBED-C1-REPAIR-01":"At least one prospectively defined all-FP32 explicit StandardScaler representation satisfies all frozen C1 criteria.","C-EMBED-C1-REPAIR-XAI-01":"The selected repaired C1 representation preserves local coefficient explanations within frozen criteria."}
for cid,text in defs.items():
 if not any(r["claim_id"]==cid for r in cr):append(claims,cf,{"claim_id":cid,"candidate_claim":text,"experiment_id":EID,"dataset_hash":old[0]["dataset_hash"],"split_hash":base["split_hash"],"config_hash":sha(ROOT/"configs/c1_fp32_preprocessing_repair.yaml"),"metric":"all_frozen_mandatory_criteria","result_artifact":"results/embedded/stage14r_claim_evaluation.csv","figure":"","git_commit":commit,"status":"UNSUPPORTED"})
dec=ROOT/"results/decisions/research_decisions.csv";dr=rows(dec);df=list(dr[0])
if not any(r["decision_id"]=="DEC-STAGE14R-001" for r in dr):append(dec,df,{"decision_id":"DEC-STAGE14R-001","timestamp":datetime.now(timezone.utc).isoformat(),"research_question":"RQ9","experiment_id":EID,"observation":"P1/P2 did not improve the frozen failure; split-mean P3/P4 reduced failed rows from 41 to 29 but remained above the relative limit. All decisions remained stable.","evidence_artifacts":"results/embedded/stage14r_error_decomposition.csv|results/embedded/stage14r_candidate_summary.csv|results/embedded/stage14r_candidate_selection.csv","interpretation":"Raw-input and mean rounding under cancellation prevent demonstrated universal explicit-FP32 preprocessing equivalence on the frozen vectors.","limitations":"Host FP32 semantics; only preregistered P0-P4; strict per-row relative criterion retained; no hardware execution.","decision":"AUTHORIZE C1 FUSED-PREPROCESSING PROTOCOL as a separate prospective experiment; do not execute or authorize quantization.","next_experiment":"C1_FUSED_PREPROCESSING_INFERENCE_PROTOCOL","git_commit":commit})
print("Stage 14R registered as completed failure; two claims UNSUPPORTED; one decision appended.")
