"""Register completed Stage-14 host FP32 equivalence and its negative claims."""
from __future__ import annotations
import csv,hashlib,subprocess
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];EID="EXP-EMBED-FP32-EQUIV-001"
def rows(p):
 with p.open(encoding="utf-8-sig",newline="") as f:return list(csv.DictReader(f))
def append(p,fields,row):
 with p.open("a",encoding="utf-8",newline="") as f:csv.DictWriter(f,fieldnames=fields).writerow(row)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
commit=subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip();legacy=ROOT/"results/registry/experiment_registry.csv";old=rows(legacy);fields=list(old[0])
if not any(r["experiment_id"]==EID for r in old):append(legacy,fields,{"experiment_id":EID,"timestamp":datetime.now(timezone.utc).isoformat(),"research_question":"Can C1 and C4 standalone host-compiled FP32 implementations satisfy frozen Stage-13 numerical equivalence?","protocol":"FROZEN_STAGE14_FP32_EQUIVALENCE","model":"MODEL-C1;MODEL-C4","representation":"STANDALONE_C11_FP32_HOST_VALIDATION","train_batches":"NONE","validation_batches":"GOLDEN_AND_BOUNDARY","test_batches":"2,6,10","seed":"DETERMINISTIC","dataset_hash":old[0]["dataset_hash"],"split_hash":next(r["split_hash"] for r in old if r["experiment_id"]=="BASE-FIXED-C1-001"),"config_hash":sha(ROOT/"configs/fp32_export_equivalence.yaml"),"git_commit":commit,"environment":"results/embedded/stage14_build_environment.json","status":"COMPLETED","metrics_artifact":"results/embedded/stage14_summary.json","model_artifact":"embedded/generated/c1|embedded/generated/c4","notes":"Scientific outcome FAILED: both candidates failed frozen preprocessing criteria despite 100% golden and boundary decisions. No quantization or MCU execution."})
claims=ROOT/"paper/claim_evidence_matrix.csv";cr=rows(claims);cf=list(cr[0]);defs={"C-EMBED-FP32-01":"MODEL-C1 standalone FP32 implementation reproduces the frozen reference within all Stage-13 criteria.","C-EMBED-FP32-02":"MODEL-C4 standalone FP32 implementation reproduces the frozen reference within all Stage-13 criteria.","C-EMBED-FP32-XAI-01":"MODEL-C1 local coefficient explanation is reproduced within separately frozen explanation criteria."}
for cid,text in defs.items():
 if not any(r["claim_id"]==cid for r in cr):append(claims,cf,{"claim_id":cid,"candidate_claim":text,"experiment_id":EID,"dataset_hash":old[0]["dataset_hash"],"split_hash":next(r["split_hash"] for r in old if r["experiment_id"]=="BASE-FIXED-C1-001"),"config_hash":sha(ROOT/"configs/fp32_export_equivalence.yaml"),"metric":"all_preregistered_mandatory_criteria","result_artifact":"results/embedded/stage14_claim_evaluation.csv","figure":"","git_commit":commit,"status":"UNSUPPORTED"})
dec=ROOT/"results/decisions/research_decisions.csv";dr=rows(dec);df=list(dr[0])
if not any(r["decision_id"]=="DEC-STAGE14-001" for r in dr):append(dec,df,{"decision_id":"DEC-STAGE14-001","timestamp":datetime.now(timezone.utc).isoformat(),"research_question":"RQ9","experiment_id":EID,"observation":"C1 and C4 preserved all golden/boundary decisions and model output tolerances but failed frozen preprocessing criteria; C1 XAI failed its relative criterion.","evidence_artifacts":"results/embedded/stage14_preprocessing_equivalence.csv|results/embedded/stage14_output_equivalence.csv|results/embedded/stage14_boundary_analysis.csv","interpretation":"Standalone FP32 arithmetic is decision-stable on the frozen set, but the full candidate cannot be called equivalent under preregistered rules.","limitations":"Host x86-64 compilation only; strict relative errors near zero; no Cortex-M execution or resource measurement.","decision":"REPAIR C1 EXPORT AND REPAIR C4 EXPORT via separately frozen preprocessing investigation; do not loosen tolerances or authorize quantization.","next_experiment":"FP32_PREPROCESSING_EQUIVALENCE_REPAIR_PROTOCOL","git_commit":commit})
print("Stage 14 registered as completed scientific failure; three claims UNSUPPORTED; one decision appended.")
